import Foundation

typealias ShadowClientHostENetPacketCodec = ShadowClientSunshineENetPacketCodec
typealias ShadowClientHostENetPacketCodecError = ShadowClientSunshineENetPacketCodecError
typealias ShadowClientHostControlMessageProfile = ShadowClientSunshineControlMessageProfile
typealias ShadowClientHostHandshakeProfile = ShadowClientSunshineHandshakeProfile
typealias ShadowClientHostProtocolProfile = ShadowClientRTSPAnnounceProfile
typealias ShadowClientHostControlChannelError = ShadowClientSunshineControlChannelError
typealias ShadowClientHostControlChannelRuntime = ShadowClientSunshineControlChannelRuntime
