import Foundation

typealias ShadowClientHostENetPacketCodec = ShadowClientSunshineENetPacketCodec
typealias ShadowClientHostENetPacketCodecError = ShadowClientSunshineENetPacketCodecError
typealias ShadowClientHostProtocolProfile = ShadowClientRTSPAnnounceProfile
