import Foundation

typealias ShadowClientHostControlChannelDefaults = ShadowClientSunshineControlChannelDefaults
typealias ShadowClientHostSessionDefaults = ShadowClientSunshineSessionDefaults
typealias ShadowClientHostENetPacketCodec = ShadowClientSunshineENetPacketCodec
typealias ShadowClientHostENetPacketCodecError = ShadowClientSunshineENetPacketCodecError
typealias ShadowClientHostControlMessageProfile = ShadowClientSunshineControlMessageProfile
typealias ShadowClientHostHandshakeProfile = ShadowClientSunshineHandshakeProfile
typealias ShadowClientHostProtocolProfile = ShadowClientRTSPAnnounceProfile
typealias ShadowClientHostControlChannelMode = ShadowClientSunshineControlChannelMode
typealias ShadowClientHostControlChannelError = ShadowClientSunshineControlChannelError
typealias ShadowClientHostControlChannelRuntime = ShadowClientSunshineControlChannelRuntime
typealias ShadowClientHostControlEncryptionCodec = ShadowClientSunshineControlEncryptionCodec
typealias ShadowClientHostInputPacketCodec = ShadowClientSunshineInputPacketCodec
